### ISSUE TITLE
Make targets for updating files on container

### ISSUE THREAD

**Issue by pstoaks** [SkiftCreative/docker-gunicorn-examples#1]
This is a bit of a mis-use of an issue, but I'm knew to this world and am wondering what the most graceful mechanism is for updating the app code in the container and refreshing/restarting gunicorn to use it?

My request would be for example Makefile targets to be added for this purpose.

And thank you very much for this example.  I'm using it to run a hug API.  Your example made it easy for this newb.

Update:  Just found the 'reload' command in gunicorn_config.py:
&#35; only use for development:
reload = True

With this I can simply copy the updated file to the container and all is well.

Nothing to do here.

**Comment by autoferrit** [comment]
@pstoaks dont forget, when using `docker run` to run your container, you can mount a local directory into the running container to change files as you edit them on the host. this is what I do for development.
 Currently, running the container is as easy as running `make run` which you can see in `Makefile`. So your run command could be updated to:

```
docker run -v ${PWD}/app:/deploy/app --name=${APP} --detach=true -p 5000:5000 ${NAMESPACE}/${APP}
```

where the change is adding `-v ${PWD}/app:/deploy/app` (`-v [host-dir]:[docker-dir]`). You may need to change the text if youre on windows. You have to use an absolute path for the host, which is why i use `${PWD}`
 And no problems about it not being an issue. I'm glad youre able to make use of it. If you have any other questions dont feel free to respond or make another issue.
